version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - pgdb
      - db

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: mysql
    ports:
        - '3308:3306'
    environment:
        MYSQL_DATABASE: 'appdb'
        MYSQL_USER: 'Alpana'
        MYSQL_PASSWORD: 'Alpana0801'
        MYSQL_ROOT_PASSWORD: 'Alpana0801'